version: '3.8'

services:
  db:
    image: postgres:13
    container_name: deribit_project-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user_db
      POSTGRES_DB: deribit_data
      TZ: Europe/Moscow
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deribit_data -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: deribit_project-app
    environment:
      DB_USER: postgres
      DB_PASSWORD: user_db
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: deribit_data

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "db", "5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
